settings:
  # Prefix for plugin messages
  prefix: "&7[&bSSJ&7] "
  
# Flight Settings
flight:
  # Maximum flight speed (1-10)
  max-speed: 2
  # Whether flight should be disabled on combat
  disable-on-combat: true

# Nickname Settings
nickname:
  # Maximum length for nicknames
  max-length: 16
  # Whether to allow color codes in nicknames
  allow-colors: true
  # Blocked words in nicknames
  blocked-words: []

# Tempban Settings
tempban:
  # Default ban reason if none provided
  default-reason: "No reason specified"
  # Maximum ban duration (in days)
  max-duration: 30
  # Whether to broadcast tempbans
  broadcast: true

# Teleport tp Settings
teleport:
  # Timeout for teleport requests (/tpr) (in milliseconds)
  teleport-request-timeout: 60000

  # Delay for using /tpr
  teleport-request-delay: 1000

  # Delay for using /warp
  teleport-warp-delay: 1000

# Ban Settings
ban:
  # Whether to broadcast bans
  broadcast: true
  # Default ban reason if none provided
  default-reason: "No reason specified"

# Kick Settings
kick:
  # Whether to broadcast kicks
  broadcast: true
  # Default kick reason if none provided
  default-reason: "No reason specified"

# Home Settings
home:
  # Maximum number of homes for ssjessentials.default
  max-homes: 3
  # Maximum number of homes for ssjessentials.mod
  max-homes-mod: 20
  # Maximum number of homes for ssjessentials.admin
  max-homes-admin: 1000


# Permissions Settings
permissions:
  # Default permission for all players
  essentials.default:
    - ssjessentials.tpr
    - ssjessentials.tpr.accept
    - ssjessentials.warp
    - ssjessentials.warp.list
    - ssjessentials.home
    - ssjessentials.home.list
    - ssjessentials.back
  
  # Permission for moderators
  essentials.mod:
    - ssjessentials.tpr
    - ssjessentials.tpr.accept
    - ssjessentials.warp
    - ssjessentials.warp.list
    - ssjessentials.home
    - ssjessentials.home.list
    - ssjessentials.sethome
    - ssjessentials.sethome.del
    - ssjessentials.sethome.edit
    - ssjessentials.sethome.reset
    - ssjessentials.ban
    - ssjessentials.tempban
    - ssjessentials.kick
    - ssjessentials.freeze
    - ssjessentials.freeze.others
    - ssjessentials.vanish
    - ssjessentials.back.other

  # Permission for admins
  essentials.admin:
    - ssjessentials.tpr
    - ssjessentials.tpr.accept
    - ssjessentials.warp
    - ssjessentials.warp.list
    - ssjessentials.home
    - ssjessentials.home.list
    - ssjessentials.sethome
    - ssjessentials.sethome.del
    - ssjessentials.sethome.edit
    - ssjessentials.sethome.reset
    - ssjessentials.setwarp
    - ssjessentials.setwarp.del
    - ssjessentials.setwarp.edit
    - ssjessentials.setwarp.reset
    - ssjessentials.resetwarp
    - ssjessentials.warpall
    - ssjessentials.spawn
    - ssjessentials.spawn.all
    - ssjessentials.setspawn
    - ssjessentials.fly
    - ssjessentials.fly.others
    - ssjessentials.feed
    - ssjessentials.feed.others
    - ssjessentials.heal
    - ssjessentials.heal.others
    - ssjessentials.god
    - ssjessentials.god.others
    - ssjessentials.vanish
    - ssjessentials.vanish.others
    - ssjessentials.freeze
    - ssjessentials.freeze.others
    - ssjessentials.kick
    - ssjessentials.kick.all
    - ssjessentials.ban
    - ssjessentials.tempban
    - ssjessentials.reload
    - ssjessentials.banlist
    - ssjessentials.nick
    - ssjessentials.nick.others
    - ssjessentials.gamemode
    - ssjessentials.gamemode.others
    - ssjessentials.kill
    - ssjessentials.kill.all
    - ssjessentials.kill.entitys
    - ssjessentials.spawn
    - ssjessentials.spawn.all
    - ssjessentials.setspawn
    - ssjessentials.back
    - ssjessentials.back.other

# Tab List Settings
tablist:
  enabled: true
  header: '&b&lWelcome to &e&lmc.saus-it.io &b&l| &e&lSSJPL'
  footer: '&7Online Players: &f%online%/%max%'
  update-interval: 20 # Update interval in ticks (20 ticks = 1 second)

# Welcome Message Settings
welcome:
  enabled: true
  # Message broadcast to all players
  broadcast_message:
    - '&b&l&m                                                                 '
    - '&b&lWelcome &e&l%player% &b&lto &e&lSauS-IT &b&l| &e&lSSJPL Server&b&l!'
    - '&b&l&m                                                                 '
  # Message shown only to the new player
  private_message:
    - '&b&l&m                                                 '
    - '&7Make sure to do &e/ssj start &7to use the SSJ Plugin.'
    - '&b&l&m                                                 '
  # Whether to show welcome message to returning players
  show_to_returning_players: false